DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
	PASS VARCHAR(10) NOT NULL,
	MAIL VARCHAR(100) NOT NULL,
	NAME VARCHAR(40) NOT NULL
);
INSERT INTO ACCOUNT (PASS, MAIL, NAME)
	VALUES('4321', 'shangxiaochi73@gmail.com', '小池 尚');
SELECT * FROM ACCOUNT;


DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
	PASS VARCHAR(10) NOT NULL,
	MAIL VARCHAR(100) NOT NULL,
	NAME VARCHAR(40) NOT NULL,
	WORDSCORE INT NOT NULL,
	ANZANSCORE INT NOT NULL
);
INSERT INTO ACCOUNT (PASS, MAIL, NAME, WORDSCORE, ANZANSCORE)
	VALUES('4321', 'shangxiaochi73@gmail.com', '小池 尚', 0, 0);
SELECT * FROM ACCOUNT;

DROP TABLE IF EXISTS WORD;
CREATE TABLE WORD (
	WORD_ID INT NOT NULL,
	WORD_VALUE VARCHAR(100) NOT NULL
);
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(1, 'パソコン');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(2, 'スマホ');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(3, 'コップ');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(4, 'お皿');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(5, 'エッセンシャルオイル');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(6, 'スプレー');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(7, '机');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(8, '椅子');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(9, '布団');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(10, '枕');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(11, 'テレビ');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(12, 'ゲーム');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(13, 'ヒーター');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(14, '畳');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(15, 'エアコン');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(16, 'ワットバイク');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(17, 'ソファー');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(18, 'トランプ');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(19, 'JAVA');
INSERT INTO WORD (WORD_ID, WORD_VALUE)
	VALUES(20, 'カーテン');
SELECT * FROM WORD;
